name: 'markets&services'
favicon: null
layout_spectrum: 0.6125408669468015
typography_spectrum: 0.0735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#ffffff'
    - '#796634'
    - '#b1ab6e'
    - '#ffd62c'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
